---
name: Anthony
surname: Schmidt
position: "PhD Student"
address: "Evaluation, Statistics, and Measurement - University of Tennessee, Knoxville"
phone: 865-236-2940
www: anthonyschmidt.co
email: "aschmi11@utk.edu"
twitter: AnthonyTeacher
github: acircleda
linkedin: 
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::hyndman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(gsheet)
```

# Education

```{r}
gsheet2tbl("https://docs.google.com/spreadsheets/d/1qbMpXHXm41q69prUVjpQFfP_mMXjORNxFP_IbAoCuKo/edit#gid=1760172285") %>%
  select(-Concentration) %>%
  detailed_entries(what = Degree, 
                   when = Year,
                   with = Institution)
```

# Publications

## Peer Reviewed Publications

```{r}
options(encoding = "UTF-8")
gsheet2tbl("https://docs.google.com/spreadsheets/d/1qbMpXHXm41q69prUVjpQFfP_mMXjORNxFP_IbAoCuKo/edit#gid=0") %>%
  filter(category=="peer-reviewed") %>%
  select(-category) %>%
  RefManageR::as.BibEntry() %>% 
  RefManageR::WriteBib("pub.bib", biblatex=F)

bibliography_entries("pub.bib") 
```

## Book Reviews

```{r}
options(encoding = "UTF-8")
gsheet2tbl("https://docs.google.com/spreadsheets/d/1qbMpXHXm41q69prUVjpQFfP_mMXjORNxFP_IbAoCuKo/edit#gid=0") %>%
  filter(category=="book review") %>%
  select(-category) %>%
  RefManageR::as.BibEntry() %>% 
  RefManageR::WriteBib("review.bib", biblatex=F)

bibliography_entries("review.bib")
```

## Technical Reports

```{r}
options(encoding = "UTF-8")
gsheet2tbl("https://docs.google.com/spreadsheets/d/1qbMpXHXm41q69prUVjpQFfP_mMXjORNxFP_IbAoCuKo/edit#gid=1473597883") %>%
  RefManageR::as.BibEntry() %>% 
  RefManageR::WriteBib("report.bib", biblatex=F)

bibliography_entries("report.bib") 
```

# Conferences

## International and National Conferences

```{r}
options(encoding = "UTF-8")
gsheet2tbl("https://docs.google.com/spreadsheets/d/1qbMpXHXm41q69prUVjpQFfP_mMXjORNxFP_IbAoCuKo/edit#gid=318960497") %>%
  filter(category=="intl") %>%
  select(-category) %>%
  RefManageR::as.BibEntry() %>% 
  RefManageR::WriteBib("conf.bib", biblatex=F)

bibliography_entries("conf.bib") 
```