# Teaching Experience
```{r teaching-experience}
gsheet2tbl("https://docs.google.com/spreadsheets/d/1qbMpXHXm41q69prUVjpQFfP_mMXjORNxFP_IbAoCuKo/edit#gid=802976282") %>%
  filter(category=="teaching") %>%
  select(-category) %>%
  tidyr::fill(-details) %>%
  vitae::detailed_entries(what = title, when = dates, with = school, where = location, details)
```


# Other Teaching Experience

```{r other-teaching-experience}
gsheet2tbl("https://docs.google.com/spreadsheets/d/1qbMpXHXm41q69prUVjpQFfP_mMXjORNxFP_IbAoCuKo/edit#gid=802976282") %>%
  filter(category=="other teaching") %>%
  select(-category) %>%
  tidyr::fill(-details) %>%
  vitae::detailed_entries(what = title, when = dates, with = school, where = location, details)
```

# Teacher Training Experience

```{r teacher-training-experience}
gsheet2tbl("https://docs.google.com/spreadsheets/d/1qbMpXHXm41q69prUVjpQFfP_mMXjORNxFP_IbAoCuKo/edit#gid=802976282") %>%
  filter(category=="teacher training") %>%
  select(-category) %>%
  tidyr::fill(-details) %>%
  vitae::detailed_entries(what = title, when = dates, with = school, where = location, details)
```
